export const actionTypes = {
  GET_FEEDBACK_DATA: "GET_FEEDBACK_DATA",
  SET_FEEDBACK_DATA: "SET_FEEDBACK_DATA",
  SET_CATEGORY: "SET_CATEGORY",
  UPDATE_VOTE: "UPDATE_VOTE",
  SORT_FEEDBACK: "SORT_FEEDBACK",
};
